settings:
  checkpoint_path: "weights/unsupervised"
  log_dir: "loggers/runs/unsupervised"
  
  model_name: "efficientnet-b2"
  device: "cuda:0"

  classes: [
    "airplane", 
    "automobile", 
    "bird", 
    "cat", 
    "deer", 
    "dog",
    "frog" ,
    "horse", 
    "ship",
    "truck"]
    
  num_epochs: 50
  print_per_iter: 10

  img_size: 32
  sup_batch_size: 128
  unsup_batch_size: 64

  lamb: 0.5
  temperature: 0.3
  beta: 0.8

  num_items: 10000